---
- name: Create i3 config directory.
  file:
    path: "{{ i3_config_directory }}"
    state: directory
    mode: "0750"

- name: Copy i3 config template.
  template:
    dest: "{{ i3_config_directory }}/config"
    src: config.j2
    mode: "0750"
